spring:
  profiles:
    active: local

logging:
  config: classpath:logback.xml
   #  file: d:/logs/boot.log

mybatis:
    type-aliases-package: com.flyhtml.payment.db.model
    mapper-locations: classpath:mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
