server:
  port: 8016
  session:
    timeout: 30

druid:
  url: jdbc:mysql://rm-uf6heaa126w5mxav7.mysql.rds.aliyuncs.com:3306/db_fly_payment?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=true
  username: xiaowei
  password: helloxiaowei
  filters: stat,slf4j
  initialSize: 10
  maxActive: 100
  maxWait: 60000
  minIdle: 5
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20

grpc:
  port: 9016

localhost: http://payment.fuliaoyi.com

wechat:
  appId: wxc995ba40913d605d
  appSecret: add3136cebac319f2ffa4b0e2a95e42b
  appKey: b81fc761fe654f619f150558c490ea49
  mchId: 1366385702
  notifyUrl: ${localhost}/notify/wechat

alipay:
  sdk:
    appId: 2017022005779574
    gateway: https://openapi.alipay.com/gateway.do
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCY8qORW0ZuK7yT44ra1Lnsuj4V1bZwRL886EcdNyx3NQ0fQ6yXi44tB39/755g3GzpfJA3DUpJFsRJhrUBOIGclwuEn8XuS9I1a5mQtm21rMlR++E97f6VpfHrshB4tBSmhIaAP4FrZs79+yglO6fIQwHSJglS8neZe/+sWlbohxfaooR23K+LJCCBcQEQRt0iZelJAU4RrFg8jNbSjODrFSb+nJL0OD7dVMybT0APH6WtMhMbSMukEGePOurf4rRZ9WkHjQH/TRjtWyrxTeJV//l9ziqQNccJDR5xv3xLKb9BLpQbg06Vk0g8CmQYb219BHtQRBRi9mBP2x1fHvQRAgMBAAECggEAfaP0kdd1B9ON2b61tgXBpaFolu80Kw2OOy5kHK/SKyq9WM1y3hqZ9IuQRTxF0jPAlBzrKw4T0+6L2Ap8bkBI2KWLpKrLIXHPgGqff60cen0x89MBuKnk1HG5RXDE7yKfRBrhkkCYw+10ZFcJJ2zV60CAIm10g1sCvGaMJL0hX2k1JS+xscFZjjIPRS6qWMpV3BNsHL4LpS7+fgaho6XxHH0iJfCjbg2f+NtVrC6/1ssyNYhRMlJN3PNPESi77zWRUO2xmy1GUblZmFsDdt0GqRH8tTU2WGlfoSSufVl5ZH6sq6JEShalTiDKdDh6nRZ2ltAYwNhzB72m4huZbu7gAQKBgQDICb2pyhRC4T+7HXzKubjdHISwqx9DFxG7dx3ngsAIrZBW8TINXyloHmbHAwDaad1gX5YXd95Awmkfkw2GDVfdzasDrVpeWrqfRgLD1igcPcpQzma4CfR/uTwlb94a8dwC6YuS3mJ5aKdJIGa39LAxHDe07axCrywTIeyF8FSVkQKBgQDDvGeWyHZt69HhxUYZRuqZc6RuFU3LIUeRxbt5z1Ev882EM7+m7oukq+Swjjkmmn9q51eDrlsAbuB1GZp0GKokyZSB9JNLo4IyWxt674y5zBXnpcocKaAYwY8Mb9bjBdciy8hJLGoCIwVnyxKWfJGWb2oAmmTmuCSK2IRhyEM2gQKBgQC8R9bZ2heJ/6NRxmZwFbD3hWErPFXXev44udxOzNVdFahW/PzEcz5w/rR0OtJxwdUZYb7O5gcuYw45JttCwopifbOqaV82kiU3xtjRZWApfMtRlYQ/UzdrhHklL48ZQ25220WA/oonhiZ2gOXN3aR9BPc198L8nQ5aD8MlKlki0QKBgE2vikGrIG3yKaP84xyHK/dpkXprlCup8rjljMoEwYlRr2DoFQnRJbVez+5PFFnA+g9Y8EAARHgAia+QUOABJg5hv0Jw6sEbjUIlLNv3FZhsask84OGal8Mbl4XtIZGLMN7LmJuKOCzO74dJbwAxQqs9XwoMPT3hGgfNdYVFsX+BAoGAeJFXTu/HwZOs08vgoGXd4D97eVuL4v3FeEpLuf01A7iPM5T8hF1jt5IDYHuX3OqP2YlZmGQIxZWquSKdIpbwpDps2ZBbJDk25RxJGlMWKuNCD522ePpOR1JSW/Fcl7W1TCoECpiZ1D2i/xw/Tda+v8mWHClqydZq0AEDsPLIxxU=
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAodJtHtkyomDQWPDmVVnIXD8dECIA0yfeY0J9VI7RsGB2n98SENyZDpNKTs1cy6+/vd3aL+B3+p194hLRZYBaQaJk007kJ/pUOaSSOkHowbycAefsLTJV9521dsCguDzM7VkHI9L730fVqi+75kb8o6VJkw0FgDCS7xSQpMFVrjmpx4hKIYlqgpKzGwoz41LR0IJXyaE0r6tgedeatIFTnkhqi/FQGSXrbUdoiODtQpXB9Q48dB7fupaxcop/2Fqqis4thxjNcUu1lhK1YocOMviqzEs2DJypdTQo2TdXtiH4GX0Eq4yW3U0NguAUd3M+D42VDl7vDoOjxxfh2EzGPwIDAQAB
    mchId: 2088102169433522
    notifyUrl: ${localhost}/notify/alipay/sdk
    signType: RSA2
    charset: UTF-8
    format: json
    timeout: 2d
  mapi:
    pId: 2088421837490657
    md5: zsustkn9wuwrhymh3omn07ohbnudxpl4
    notifyUrl: ${localhost}/notify/alipay/mapi

payment:
    key: Y5W8bP6WffJqE84S2L6pCXG8nNIkJN66jy7A01dyIV6I

